POST {{host}}/transaction
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3MzMyOTM2MDcsImV4cCI6MTczMzM4MDAwNywiZW1haWwiOiJ0cnVvbmczQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.ppBf73ZMM9E3v7iTwpFB1h0xdach6grA2xta2QV5dz4yNOSG6w47joONiamGMc_N

{
  "bookId": 5,
  "userId": 8
}
###
PUT {{host}}/transaction/9
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3MzMyOTM2MDcsImV4cCI6MTczMzM4MDAwNywiZW1haWwiOiJ0cnVvbmczQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.ppBf73ZMM9E3v7iTwpFB1h0xdach6grA2xta2QV5dz4yNOSG6w47joONiamGMc_N

###
GET {{host}}/transaction
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3MzMyOTM2MDcsImV4cCI6MTczMzM4MDAwNywiZW1haWwiOiJ0cnVvbmczQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.ppBf73ZMM9E3v7iTwpFB1h0xdach6grA2xta2QV5dz4yNOSG6w47joONiamGMc_N
